# A generic, single-database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = app/db/migrations

# template used to generate new migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# prepend VENV_PATH/lib/python3.x/site-packages to sys.path
sys.path = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to use for slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported from sys.path
# prepend_sys_path = false

version_locations = %(here)s/app/db/migrations/versions

# version path separator; defaults to os.pathsep.
# Use os.pathsep to separate multiple version directories
# version_path_separator = :

# set to 'true' to search source files recursively
# recursive_version_locations = false

# logging configuration is handled via logging.config.fileConfig in env.py

[post_write_hooks]
# post_write_hooks defines scripts that are run after a revision is generated
# e.g., auto-formatting Python code:
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARNING" logs neither.

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
