import logging
from typing import List
from uuid import UUID
from fastapi import APIRouter, Depends, Path, Body, status
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import get_current_active_user
from app.models.user import User
from app.schemas.dashboard import (
    ReportGenerateRequest,
    GeneratedReportResponse
)
from app.services.reports import ReportService

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post("/generate", response_model=GeneratedReportResponse, status_code=status.HTTP_201_CREATED)
async def generate_academic_report(
    payload: ReportGenerateRequest = Body(...),
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """Generates an academic report file (PDF/Excel/CSV) and indexes metadata."""
    svc = ReportService(db)
    return await svc.generate_report(
        generated_by_id=current_user.id,
        report_type=payload.report_type,
        export_format=payload.format,
        filters=payload.filters
    )


@router.get("/", response_model=List[GeneratedReportResponse])
async def list_generated_reports(
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """Lists reports generated by the current user."""
    svc = ReportService(db)
    return await svc.get_user_reports(current_user.id)


@router.get("/{id}/download")
async def download_report_file(
    id: UUID = Path(...),
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """Downloads generated report file."""
    svc = ReportService(db)
    report = await svc.get_report_by_id(id)
    return FileResponse(
        path=report.file_path,
        filename=f"{report.report_type}_report.{report.format}",
        media_type="application/octet-stream"
    )
